
export const FETCH_PLAYERS = 'FETCH_PLAYERS';
export const FETCH_MATCHES= 'FETCH_MATCHES';
export const FETCH_TOURNAMENTS='FETCH_TOURNAMENTS';
export const SAVE_MATCH_TO_FAVORITES = 'SAVE_MATCH_TO_FAVORITES';


